// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYW7pCHAtauHHiI_oqILPYV08jr_C96UA',
    appId: '1:739921343400:web:d6cd4e21dee9cc3cede39d',
    messagingSenderId: '739921343400',
    projectId: 'fortisenha-f431b',
    authDomain: 'fortisenha-f431b.firebaseapp.com',
    storageBucket: 'fortisenha-f431b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLAmavA_sJxi74dtFG1kJy5hfLmbKqwM',
    appId: '1:739921343400:android:535a265cc9e25551ede39d',
    messagingSenderId: '739921343400',
    projectId: 'fortisenha-f431b',
    storageBucket: 'fortisenha-f431b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBVJiDrEgabtPe_N7TTfxJoJedzIy6ysA',
    appId: '1:739921343400:ios:6184b4775ed365f6ede39d',
    messagingSenderId: '739921343400',
    projectId: 'fortisenha-f431b',
    storageBucket: 'fortisenha-f431b.firebasestorage.app',
    iosBundleId: 'com.example.fortisenha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBVJiDrEgabtPe_N7TTfxJoJedzIy6ysA',
    appId: '1:739921343400:ios:6184b4775ed365f6ede39d',
    messagingSenderId: '739921343400',
    projectId: 'fortisenha-f431b',
    storageBucket: 'fortisenha-f431b.firebasestorage.app',
    iosBundleId: 'com.example.fortisenha',
  );
}
